keys:
  - &taneb_user ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPPE+hjAIQBKvf3GxYrcX4ImpbPPz17ZdCpL4C8a3Hif
creation_rules:
  - path_regex: home/users/taneb/kubeconfig\.yaml$
    key_groups:
    - age: [*taneb_user]
  - path_regex: home/users/taneb/secrets\.yaml$
    key_groups:
    - age: [*taneb_user]
