# For hosts where ~/.zshrc is managed outside Nix.
#
# home-manager only sources its session variables when it manages the shell, so
# without this snippet home.sessionVariables has no effect. The zz- prefix sorts
# it after the other ~/.zshrc.d scripts.
{ ... }:

{
  home.file.".zshrc.d/zz-home-manager.zsh".text = ''
    # Generated by home-manager. Do not edit.

    if [ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then
      . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
    fi

    case ":$PATH:" in
      *":$HOME/.nix-profile/bin:"*) ;;
      *) export PATH="$HOME/.nix-profile/bin:$PATH" ;;
    esac
  '';
}
